### ISSUE TITLE
build custom model error

### ISSUE THREAD

**Issue by mokiki1** [sunlicai/MAE-DFER#3]
Thanks for your work.
I have an error.When I run "finetune_local_global_attn_depth16_region_size2510_with_diff_target_164.sh", an error apperance,it seems the model name error. The dataset is DFEW,some config has edited. Can you support some solutions?

Traceback (most recent call last):
  File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 679, in <module>
    main(opts, ds_init)
  File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 332, in main
    model = create_model(
  File "D:\anaconda\envs\Pytorch_GPU\lib\site-packages\timm\models\factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (vit_base_dim512_no_depth_patch16_224)

**Comment by youcaiSUN** [comment]
Hi, thanks for your interest in our work!

The reason is that 'vit_base_dim512_no_depth_patch16_224' is not defined in model_finetuning.py. Due to the limited computational resources, we can only pre-train the model at the size of 160x160 instead of 224x224.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/09/2023 17:34 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [sunlicai/MAE-DFER] build custom model error (Issue #3) |

Thanks for your work.
I have an error.When I run "finetune_local_global_attn_depth16_region_size2510_with_diff_target_164.sh", an error apperance,it seems the model name error. The dataset is DFEW,some config has edited. Can you support some solutions?

Traceback (most recent call last):
File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
pydev_imports.execfile(file, globals, locals) # execute the script
File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 679, in
main(opts, ds_init)
File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 332, in main
model = create_model(
File "D:\anaconda\envs\Pytorch_GPU\lib\site-packages\timm\models\factory.py", line 78, in create_model
raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (vit_base_dim512_no_depth_patch16_224)

**Comment by mokiki1** [comment]
Hello, there is another issue now. The following error was reported during back propagation during training. Can you provide some help?
Traceback (most recent call last):
  File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 680, in <module>
    main(opts, ds_init)
  File "E:/code/ME/MAE-DFER-master/run_class_finetuning.py", line 583, in main
    train_stats = train_one_epoch(
  File "E:\code\ME\MAE-DFER-master\engine_for_finetuning.py", line 93, in train_one_epoch
    grad_norm = loss_scaler(loss, optimizer, clip_grad=max_norm,
  File "E:\code\ME\MAE-DFER-master\utils.py", line 349, in __call__
    self._scaler.scale(loss).backward(create_graph=create_graph)
  File "D:\anaconda\envs\Pytorch_GPU\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\anaconda\envs\Pytorch_GPU\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 8, 512]], which is output 0 of AsStridedBackward0, is at version 2; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by youcaiSUN** [comment]
Sorry, I never met this issue before. Did you use the required version of python packages (e.g., pytorch1.7.1) shown in Installation?BTW, did you change the code?

**Comment by Huangzhw0221** [comment]
I met this error too,and i solved it correctly. Here I will give out my solution, and maybe that will help you.
The key reason is that the tensor is 'updated' or computed twice, so you are required to clone it before backward operation.
The error happened in model_finetuning.py -> LGBlock -> near line 290,310, under 'if not self.no_second:' and 'if not self.no_third:' .
You can use: 'messenger_tokens = x[:,0].clone()'  and 'local_tokens = x[:,1:].clone() ' to replace the original code:'messenger_tokens = x[:,0]' and 'local_tokens = x[:,1:]'. By doing this, you can keep the tensor only be operated by one optimizer during bacaward operation. 

Good Luck!

**Comment by youcaiSUN** [comment]
Thanks very much for your kindful solution! @Huangzhw0221
